src/Entity/MemoEdit.php
<?php

namespace App\Entity;

use App\Repository\MemoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MemoRepository::class)
 */
class MemoEdit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Content;

    /**
     * @var @ORM\Column(type="string")
     */
    private $path;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param mixed $path
     * @return Memo
     */
    public function setPath($path)
    {
        $this->path = $path;
        return $this;
    }

}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\ContentLister\ContentSearch;
use App\Security\File\Sanitizer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\String\u;

class SearchController extends AbstractController
{
    /**
     * @Route("/search/", name="search")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @param ContentSearch $contentSearch
     * @param Request $request
     * @return Response
     */
    public function search(ContentSearch  $contentSearch, Request $request): Response
    {
        $result = [];
        $searchText = '';
        if ($request->getMethod() === 'POST'
            && $this->isCsrfTokenValid('search', $request->request->get('_csrf_token'))
        ) {
            $searchText = $request->request->get('searchText');
            $result = $contentSearch->findContent($searchText);
        }

        return $this->render('search/index.html.twig', ['name' => $searchText, 'result' => $result, 'searchText' => $searchText]);
    }

    /**
     * @Route("/search_result/{type}/{name}", name="search_result")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @param string $type
     * @param string $path
     * @return Response
     */
    public function searchResult(string $type, string $path): Response
    {
        $path = urldecode($path);
        if ($path->afterLast('.')->toString() !== 'md') {
            return $this->redirectToRoute('file', ['path' => urlencode($path->toString())]);
        }
        if ($path->startsWith('/Wiki')) {
            return $this->redirectToRoute('wiki_show', ['path' => urlencode($path->after('/Wiki/')->beforeLast('.'))]);
        }
        if ($path->endsWith('Linksammlung.md')) {
            return $this->redirectToRoute('link-collection');
        }
        if ($path->endsWith('neu_dabei.md')) {
            return $this->redirectToRoute('newbees');
        }
        return $this->redirectToRoute('memo', ['path' => urlencode($path)]);
    }
}

templates/search/index.html.twig
{% extends 'layout/conatiner_fluid.html.twig' %}

{% block title %}{{ 'title'|trans({'%name%': name}, 'search') }}{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <div class="card card">
            <div class="card-header">{{ 'headline'|trans({}, 'search') }}</div>
            <div class="card-body">
                <form method="post">
                    <div class="row card-text">
                        <div class="col col-md-10 col-sm-10">
                            <input type="text" value="{{ searchText }}" name="searchText" id="inputSearchText" class="form-control py-4" required autofocus>
                        </div>
                        <div class="col">
                            <input type="hidden" name="_csrf_token" value="{{ csrf_token('search') }}" >
                            <button class="btn btn-lg btn-partei" type="submit">
                                {{ 'search'|trans({}, 'search') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div style="height: 30px"></div>
        {% if app.request.method == "POST" %}
            <div class="card card">
                <div class="card-header">{{ 'results.headline'|trans({}, 'search') }}</div>
                <div class="card-body">
                    <div class="list-group">

                        {% if result|length == 0 %}
                            <div class="alert alert-warning" role="alert">
                                {{ 'results.no'|trans({}, 'search') }}
                            </div>
                        {% else %}
                            {% if result.folder is defined %}
                                {% for result in result.folder %}
                                    <a href="{{ path('search_result', {'name': result.name|url_encode, 'type': 'folder'}) }}" class="list-group-item list-group-item-action">
                                        {{ result.name }}
                                    </a>
                                {% endfor %}
                            {% endif %}
                            {% if result.files is defined %}
                                {% for result in result.files %}
                                  <a href="{{ path('search_result', {'name': result.name|url_encode, 'type': 'file'}) }}" class="list-group-item list-group-item-action">
                                        {{ result.name }}
                                    </a>
                                {% endfor %}
                            {% endif %}
                            {% if result.content is defined %}
                                {% for result in result.content %}
                                    <a href="{{ path('search_result', {'name': result.name|url_encode, 'type': 'content'}) }}" class="list-group-item list-group-item-action">
                                        {{ result.name }}
                                    </a>
                                {% endfor %}
                            {% endif %}

                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}